version: "3.8"

services:
  ws:
    image: realstraw/sbt
    working_dir: /acdc/ws
    volumes:
      - ./:/acdc/ws
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 9001:9000
    tty: true # for easy debugging
    # command:
    #   sbt ws/run
  db:
    image: postgres
    volumes:
      - acdc-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432
  flyway:
    image: flyway/flyway:latest-alpine
    volumes:
      - ./flyway/sql:/flyway/sql
    environment:
      FLYWAY_URL: "jdbc:postgresql://db:5432/postgres"
      FLYWAY_USER: "postgres"
      FLYWAY_PASSWORD: "${POSTGRES_PASSWORD}"
    depends_on:
      - db
    command:
      migrate

volumes:
  acdc-postgres-data:
