version: "3.8"

services:
  ws:
    image: scala-sbt-dev
    working_dir: /acdc/ws
    volumes:
      - ./:/acdc/ws
    environment:
      DMP_ARTIFACTORY_HOST: "${DMP_ARTIFACTORY_HOST}"
      DMP_ARTIFACTORY_USER: "${DMP_ARTIFACTORY_USER}"
      DMP_ARTIFACTORY_PASSWORD: "${DMP_ARTIFACTORY_PASSWORD}"
      POSTGRES_PASSWORD: "acdc"
    ports:
      - 9001:9000
    command:
      sbt ws/run
  db:
    image: postgres
    volumes:
      - acdc-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "acdc"

volumes:
  acdc-postgres-data:
